### ISSUE TITLE
Simplify types

### ISSUE THREAD

**Issue by alex-slynko** [akshaymankar/dhall-concourse#4]
Do we even need to keep the complex recursion for the possible Concourse types?

Maybe it is better to add the limitations where it is only possible to put `on_parallel` just on the top level and do only once in the `on_parallel`. This might reduce compilation time and the complexity.

**Comment by akshaymankar** [comment]
Sometimes it is nice to be able to do something like this:

```yaml
in_parallel:
- do:
   - task: something
   - task: something
- task: something
```
Also, it would be required for step hooks.
